### ISSUE TITLE
BlogPostRepository bug

### ISSUE THREAD

**Issue by fibona44i** [dimafeng/dimafeng-examples#1]
```
class BlogPostRepositoryImpl @Autowired()(mongoTemplate: MongoTemplate) extends BlogPostRepositoryCustom {
  override def addCategoryToBlogPostId(blogPostId: String, categoryId: Array[String]): Unit =
    mongoTemplate.findAndModify(
      MO("_id" -> new ObjectId(blogPostId)).toQuery,
      $addToSet("categoryIds" -> categoryId).toUpdateWithLock,
      classOf[BlogPost])
}

```

Hi! It seems like categoryId will be added to categoryIds field as array which is wrong, it should be added using each operator. Can you confirm?

**Comment by dimafeng** [comment]
@fibona44i you're right. This's a bug, I don't know how I missed that. I'll fix this as soon as I can.

**Comment by dimafeng** [comment]
fixed https://github.com/dimafeng/dimafeng-examples/commit/7becf35202818e3675335492baf1727b8ddcd0e2
